// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwkqjmevayjznfpqewom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3a3FqbWV2YXlqem5mcHFld29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzM0MDksImV4cCI6MjA1ODYwOTQwOX0.abjElIuQUnN496x6X7FcawZ04XGqI7cdK3SpjWdCMgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);